### PR TITLE
Fix 67

### LINKED ISSUE #67: Scoped Key update needed for Java SDK
It looks like the Scoped Key structure has changed. The master keys were 32 characters long, but the newer projects have 64 character master keys. This may have been modified in other libraries but does not appear to have been updated in the JS library yet.

This was noticed when a customer began receiving an InvalidKeyException error while attempting to encrypt using the new master API key.

### PR DESCRIPTION
**Pull request by dkador**
this should fix #67.

### CODE REVIEW

File: gradle.properties [hunk 1]
```diff
@@ -1,4 +1,4 @@
-VERSION_NAME=2.1.2
+VERSION_NAME=2.1.3
```
Comment (Geeber) [inline gradle.properties]: Nit: I think this could arguably be a minor version bump (i.e. `2.2.0`), not a patch version bump. The definitions (from http://semver.org/):

```
MINOR version when you add functionality in a backwards-compatible manner, and
PATCH version when you make backwards-compatible bug fixes.
...
A bug fix is defined as an internal change that fixes incorrect behavior.
```

I guess it's fuzzy whether this is a "bug fix" or "added functionality". I'd say the latter but if you think it's the former that's reasonable, just wanted to call out the distinction explicitly.

File: gradle.properties [hunk 2]
```diff
@@ -1,4 +1,4 @@
...
 VERSION_CODE=9
```
Comment (Geeber) [inline gradle.properties]: I think you also need to bump the `VERSION_CODE` to `10`; it might not actually matter but I vaguely recall that it might be used by some portion of the Android build logic.

File: core/src/main/java/io/keen/client/java/ScopedKeys.java [hunk 3]
```diff
@@ -63,7 +63,11 @@
      */
     public static String encrypt(String apiKey, Map<String, Object> options)
             throws ScopedKeyException {
-        return encrypt(KeenClient.client(), apiKey, options);
+        if (apiKey.length() == 64) {
+            return encrypt(KeenClient.client(), apiKey, options);
+        } else {
+            return oldEncrypt(KeenClient.client(), apiKey, options);
```
Comment (Geeber) [inline core/src/main/java/io/keen/client/java/ScopedKeys.java]: Suggestion: maybe call these `encrypt64CharacterKey` and `encrypt32CharacterKey` or something instead of `encrypt` and `oldEncrypt`; the latter doesn't provide a lot of insight into the difference, and will just need to get renamed again if/when we change the algorithm again.

**Comment by Geeber** [comment]
:+1: with a couple very minor suggestions. I didn't review the details of the algorithm super closely as I don't know how it's supposed to work, but I assume that the unit test would catch any problem.

File: gradle.properties (hunk 2 above)
Comment (dkador) [inline gradle.properties]: good call - done.

File: gradle.properties (hunk 1 above)
Comment (dkador) [inline gradle.properties]: agreed with you. good reminder.

File: core/src/main/java/io/keen/client/java/ScopedKeys.java (hunk 3 above)
Comment (dkador) [inline core/src/main/java/io/keen/client/java/ScopedKeys.java]: We need to leave one as `encrypt` for API contract reasons. But I agree that `oldEncrypt` is a bad name so I've fixed that.

Comment (Geeber) [inline core/src/main/java/io/keen/client/java/ScopedKeys.java]: Ah, yeah sorry I didn't notice that the one taking a `KeenClient` was also `public`. Makes sense.
